_commit: d6f5ff0
_src_path: gh:monarch-initiative/koza-ingest-template
copyright_year: '2026'
email: kevin@tislab.org
full_name: Kevin Schaper
github_handle: monarch-initiative
github_org: monarch-initiative
license: MIT
project_description: Monarch KG ingest for phenotypes from HPOA
project_name: monarch-phenotype-profile-ingest
project_slug: monarch_phenotype_profile_ingest
